### PR TITLE
Update to fluent assertions 5 - take 2

### PR DESCRIPTION
**Pull request by rikrak**
Fixed an issue whereby running the Unit Tests in the Release build configuration would result in failures, whereas using the Debug configuration would not.

Unit test projects now build in Debug mode for the Release build configuration.  This allows the FluentAssertions library to run in a consistent manner.

### CODE REVIEW

**Comment by rikrak** [comment]
Hmmm.  Well that didn't work :-(

**Comment by rikrak** [comment]
Yahoo!

**Comment by kevinkuszyk** [comment]
@rikrak thanks again for the contribution.  I'll get a beta up onto nuget soon.

**Comment by kevinkuszyk** [comment]
@rikrak I just pushed `0.7.0-beta1` to nuget.  You should see it on the site in an hour or so.

**Pull request merged**
