### PR TITLE
Added JsonResult Assertions

### PR DESCRIPTION
**Pull request by rikrak**
Hi,

I've needed some Json Result tests recently, so I wondered if you'd like them in your project.

Feel free to offer suggestions/amendments.  For example I wasn't sure about the WithData assertion that took a predicate as it is inconsistent with other parts of the API.

Hopefully I've not buggered up the branch this time :-)

### CODE REVIEW

**Comment by kevinkuszyk** [comment]
Looks good.  Just a couple of comments:

1. Can you remove the compiler directives?  We moved the MVC Core code out into it's own repro a while ago.  I thought I'd removed the compiler directives from the code here, but on inspection today I see we still have them.  We only compile for the full clr now, so there's no need to have them in any new code.  I've also added #38 to track removing them for existing code.  A PR for that would also be appreciated!
2. There's some commented out tests - can these be removed too?

Do you think this covers off everything we need for #10?  I honestly don't recall what I had in mind for that.

-----------

ps. I see from your profile your in Harrogate.  Do you ever get down to Leeds Sharp?  If so, we should grab a beer after one sometime?

**Comment by rikrak** [comment]
> ps. I see from your profile your in Harrogate. Do you ever get down to Leeds Sharp? If so, we should grab a beer after one sometime?

I haven't been to Leeds Sharp. I used to go to Agile Yorkshire when I worked in Leeds, but I now work in Harrogate, so it's more of a bind to get into leeds for these things.  I'll ping you if I'm around though :-)

**Comment by rikrak** [comment]
> Do you think this covers off everything we need for #10?
Ah! I hadn't spotted that.  It might do, or at least it's a start.  There's not a lot of detail in the issue as to what is required

**Comment by kevinkuszyk** [comment]
Thanks again for your contributions.  It's all in in 0.8.0 which should be up on NuGet shortly.

Are you also @rikrak on Twitter?  Lets keep in touch there about events in Leeds / Yorkshire and further afield.

**Pull request merged**
